=== jboss-developer/jboss-eap-quickstarts/jboss-as-xml-dom4j/src/main/resources/catalog.xsd
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
  <xsd:element name="catalog">
    <xsd:complexType>
      <xsd:sequence>
        <xsd:element name="book" 
                     minOccurs="0" 
                     maxOccurs="unbounded">
           <xsd:complexType>
              <xsd:sequence>
                 <xsd:element name="author" type="xsd:string"/>
                 <xsd:element name="title" type="xsd:string"/>
                 <xsd:element name="genre" type="xsd:string"/>
                 <xsd:element name="price" type="xsd:float"/>
                 <xsd:element name="publish_date" type="xsd:date"/>
                 <xsd:element name="description" type="xsd:string"/>
                 </xsd:sequence>
              <xsd:attribute name="id" type="xsd:string"/>
           </xsd:complexType>
        </xsd:element>
      </xsd:sequence>
    </xsd:complexType>
  </xsd:element>
</xsd:schema>

=== jboss-developer/jboss-eap-quickstarts/jboss-as-xml-dom4j/src/main/resources/catalog.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!-- JBoss, Home of Professional Open Source Copyright 2012, Red Hat, Inc. 
    and/or its affiliates, and individual contributors by the @authors tag. See 
    the copyright.txt in the distribution for a full listing of individual contributors. 
    Licensed under the Apache License, Version 2.0 (the "License"); you may not 
    use this file except in compliance with the License. You may obtain a copy 
    of the License at http://www.apache.org/licenses/LICENSE-2.0 Unless required 
    by applicable law or agreed to in writing, software distributed under the 
    License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS 
    OF ANY KIND, either express or implied. See the License for the specific 
    language governing permissions and limitations under the License. -->
<catalog xsi:noNamespaceSchemaLocation="catalog.xsd" 
      xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
	<book id="bk101">
		<author>Sean Connery</author>
		<title>Off the Book Bond Adventures</title>
		<genre>Action</genre>
		<price>44.95</price>
		<publish_date>2010-10-01</publish_date>
		<description>007 adventures in japan!
		</description>
	</book>
	<book id="bk10@">
		<author>Scott Card</author>
		<title>Enders Game</title>
		<genre>SciFi</genre>
		<price>44.95</price>
		<publish_date>2000-10-01</publish_date>
		<description>AAALIENS!</description>
	</book>
</catalog>
